### ISSUE TITLE
Calling `contains` with large coordinates causes panic due to overflow

### ISSUE THREAD

**Issue by Snoeprol** [georust/geo#921]
**updated description by @michaelkirk:**

Calling `contains` with large coordinates causes panic due to overflow.

```
let world: Polygon<i32> = polygon![
    (x: 43348848, y: 114780793),
    (x: 93348848, y: 214865793),
    (x: 13518848, y: 714848793),
    (x: 23518848, y: 814780793),
    (x: 63348848, y: 914780793),
];

let point: Point<i32> = Point::new(53348922, 514780838);
```

crash output:
```
attempt to multiply with overflow
thread 'algorithm::contains::polygon::tests::gh_issue_921' panicked at 'attempt to multiply with overflow', /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/arith.rs:369:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: <i32 as core::ops::arith::Mul>::mul
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/arith.rs:362:45
   4: geo::algorithm::kernels::Kernel::orient2d
             at ./src/algorithm/kernels/mod.rs:31:19
   5: geo::algorithm::intersects::line::<impl geo::algorithm::intersects::Intersects<geo_types::geometry::coordinate::Coordinate<T>> for geo_types::geometry::line::Line<T>>::intersects
             at ./src/algorithm/intersects/line.rs:11:9
   6: geo::algorithm::coordinate_position::coord_pos_relative_to_ring
             at ./src/algorithm/coordinate_position.rs:376:12
   7: <geo_types::geometry::polygon::Polygon<T> as geo::algorithm::coordinate_position::CoordinatePosition>::calculate_coordinate_position
             at ./src/algorithm/coordinate_position.rs:245:15
   8: geo::algorithm::coordinate_position::CoordinatePosition::coordinate_position
             at ./src/algorithm/coordinate_position.rs:38:9
   9: geo::algorithm::contains::polygon::<impl geo::algorithm::contains::Contains<geo_types::geometry::coordinate::Coordinate<T>> for geo_types::geometry::polygon::Polygon<T>>::contains
             at ./src/algorithm/contains/polygon.rs:16:9
  10: geo::algorithm::contains::polygon::<impl geo::algorithm::contains::Contains<geo_types::geometry::point::Point<T>> for geo_types::geometry::polygon::Polygon<T>>::contains
             at ./src/algorithm/contains/polygon.rs:25:9
  11: geo::algorithm::contains::polygon::tests::gh_issue_921
             at ./src/algorithm/contains/polygon.rs:163:17
  12: geo::algorithm::contains::polygon::tests::gh_issue_921::{{closure}}
             at ./src/algorithm/contains/polygon.rs:135:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**original report:**
Hi all, 

Just wanted to note that the contains functions shows some really weird behaviour for i32 types close to i32 max.

```rust
let poly_32 = polygon![point(107374182, 107374182) , point(207374182, 107374182) , point(207374182, 207374182) , point(107374182, 207374182) ]

let point = point(107374182, 107374182) 

poly_32.contains(&point)
```

crashes. 

Cheers :)!

**Comment by michaelkirk** [comment]
I'm not able to reproduce this crash - I tried in #922.

Can you share any more details about your issue? Preferably in the form of code and the log snippet of the crash that occurs within that code.

**Comment by michaelkirk** [comment]
Ok, I've updated the description with the appropriate details. 

It seems like a pretty straight forward overflow issue. Can you use i64 geometries instead of i32?

Also, the geometry you supplied is not valid in the OGC sense - it crosses over itself:
<img width="269" alt="Screen Shot 2022-10-14 at 10 36 21 AM" src="https://user-images.githubusercontent.com/217057/195907771-2e3568e8-1a7e-483c-925e-eab869507c70.png">

Be aware that many of our algorithms won't work with invalid geometries.
